<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Compartido\CgPos.Dominio\CgPos.Dominio.csproj" />
    <ProjectReference Include="..\..\Compartido\CgPos.Contratos\CgPos.Contratos.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
